In [1]:
import numpy as np

In [2]:
from time import process_time

In [9]:
python_list = [ i for i in range (100000000)]
start_time = process_time()
python_list = [ i+5 for i in python_list ]
end_time = process_time()
print(end_time - start_time)

4.796875


In [11]:
np_array = np.array( [i for i in range (100000000)])
start_time1 = process_time()
np_array = np_array + 5
end_time1 = process_time()
print(end_time1 - start_time1)

0.09375


In [12]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [14]:
#creating a 1 dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a.shape

(4,)

In [16]:
#creating a 2 dimension array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
b.shape

(2, 4)

In [19]:
c = np.array([(1,2,3,4),(5,6,7,8)] , dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [21]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
#array of a particular value
z = np.full((6,3),7)
print(z)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [26]:
#identity matrix

q=np.eye(7)
print(q)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [27]:
t=np.random.random((3,4))
print(t)

[[0.58810867 0.95412755 0.28488872 0.29725026]
 [0.48144181 0.7368874  0.26423206 0.48283122]
 [0.73232536 0.10562094 0.80942689 0.94476834]]


In [28]:
g= np.random.randint(10,100,(2,6))
print(g)

[[73 71 77 13 94 28]
 [27 95 14 91 73 99]]


In [30]:
#evenly spaced value - specifying the number of values required
h=np.linspace(10,40,6)
print(h)

[10. 16. 22. 28. 34. 40.]


In [32]:
#evenly spaced value -  specifying the step
i=np.arange(10,40,6)
print(i)

[10 16 22 28 34]


In [33]:
#convert a list to numpy array
list2=[10,20,30,56,77]
np_array=np.asarray(list2)
print(np_array)

[10 20 30 56 77]


In [34]:
type(np_array)

numpy.ndarray

ANALYSING a NUMPY ARRAY

In [35]:
k = np.random.randint(20,99,(5,5))
print(k)

[[77 41 49 41 79]
 [98 32 55 90 38]
 [98 68 74 31 93]
 [87 89 85 68 64]
 [31 31 77 29 20]]


In [37]:
print(k.shape)

(5, 5)


In [38]:
print(k.ndim)

2


In [40]:
print(k.size) #number of elements in an array

25


In [41]:
print(k.dtype)

int32


Mathematical Operations on a Numpy Array

In [55]:
list1=[1,2,3,4,5]
list2=[3,4,5,6,7]

print(list1+list2) #it just concatinate
print(np.add(list1,list2))

[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[ 4  6  8 10 12]


In [44]:
a = np.random.randint(0,10, (3,3))

b = np.random.randint(10,20 , (3,3))
                      

In [45]:
print(a)

[[6 2 3]
 [6 3 3]
 [5 1 1]]


In [46]:
print(b)

[[12 11 17]
 [14 15 11]
 [15 16 13]]


In [47]:
print(a+b)

[[18 13 20]
 [20 18 14]
 [20 17 14]]


In [49]:
print(a-b)

[[ -6  -9 -14]
 [ -8 -12  -8]
 [-10 -15 -12]]


In [50]:
print(a*b)

[[72 22 51]
 [84 45 33]
 [75 16 13]]


In [51]:
print(a/b)

[[0.5        0.18181818 0.17647059]
 [0.42857143 0.2        0.27272727]
 [0.33333333 0.0625     0.07692308]]


ARRAY MANIPUALTION

In [57]:
array1 = np.random.randint(2,30,(4,3))
print(array1)
print(array1.shape)

[[27  4 22]
 [19 27  4]
 [28  3 22]
 [ 5 21 10]]
(4, 3)


In [61]:
transpose_array = np.transpose(array1) #transpose
print(transpose_array)
print(transpose_array.shape)

[[27 19 28  5]
 [ 4 27  3 21]
 [22  4 22 10]]
(3, 4)


In [62]:
array2 = transpose_array.T
print(array2)
print(array2.shape)

[[27  4 22]
 [19 27  4]
 [28  3 22]
 [ 5 21 10]]
(4, 3)


Reshaping the ARRAY

In [64]:
k=np.random.randint(0,10,(2,3))
print(k)
print(k.shape)

[[2 5 4]
 [2 8 6]]
(2, 3)


In [66]:
j=k.reshape(3,2)
print(j)
print(j.shape)

[[2 5]
 [4 2]
 [8 6]]
(3, 2)


In [ ]:
j=k.reshape(4,2)
print(j)
print(j.shape